In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Índice
1. [28. Cargar y Verificar Datos](#28-Cargar-y-Verificar-Datos)
2. [29. Limpieza de Datos](#29-Limpieza-de-Datos)
3. [Conclusiones](#conclusiones)

## 28. Cargar y Verificar Datos

In [18]:
# Cargar datos en CSV

artistas_rendimiento = pd.read_csv("tb_artistas_rendimiento.csv", sep=";")
canciones_estadisticas = pd.read_csv("tb_canciones_estadisticas.csv", sep=";")
generos_por_temporada = pd.read_csv("tb_generos_por_temporada.csv", sep=";")
perfil_oyentes = pd.read_csv("tb_perfil_oyentes.csv", sep=";")
streaming_mensual = pd.read_csv("tb_streaming_mensual.csv", sep=";")

####  Verificacion artistas_rendimiento

In [ ]:
print(artistas_rendimiento.shape)

(200, 18)

In [20]:
print(artistas_rendimiento.dtypes)

artista_id                        int64
nombre_artistico                 object
genero_principal                 object
pais_origen                      object
anio_debut                        int64
seguidores                        int64
verificado                        int64
sello_discografico               object
num_canciones                     int64
num_canciones_en_chart            int64
total_streams                     int64
streams_promedio_por_cancion    float64
puntuacion_media                float64
bailabilidad_media              float64
energia_media                   float64
mejor_posicion_chart              int64
total_semanas_chart               int64
num_playlists_total               int64
dtype: object

In [21]:
artistas_rendimiento.head()

,artista_id,nombre_artistico,genero_principal,pais_origen,anio_debut,seguidores,verificado,sello_discografico,num_canciones,num_canciones_en_chart,total_streams,streams_promedio_por_cancion,puntuacion_media,bailabilidad_media,energia_media,mejor_posicion_chart,total_semanas_chart,num_playlists_total
0,1,La Casa Azul,rock,España,1953,2446340,0,Independiente,8,7,13778,1722.25,3.77,0.42,0.73,3,16,31
1,2,Recycled J,rap,España,1967,15150607,0,Columbia Records,12,12,36218,3018.17,3.85,0.77,0.81,1,29,50
2,3,El Guincho,r&b,España,1961,6683728,1,Sony Music,11,11,19504,1773.09,3.75,0.64,0.59,1,30,39
3,4,Los Secretos,pop,España,1961,4664712,1,TuneCore,6,5,11227,1871.17,3.38,0.69,0.66,4,12,19
4,5,Duncan Dhu,clasica,España,1953,948124,1,Astralwerks,7,6,24190,3455.71,3.65,0.17,0.26,13,18,34

In [22]:
artistas_rendimiento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   artista_id                    200 non-null    int64
 1   nombre_artistico              200 non-null    object
 2   genero_principal              200 non-null    object
 3   pais_origen                   200 non-null    object
 4   anio_debut                    200 non-null    int64
 5   seguidores                    200 non-null    int64
 6   verificado                    200 non-null    int64
 7   sello_discografico            200 non-null    object
 8   num_canciones                 200 non-null    int64
 9   num_canciones_en_chart        200 non-null    int64
 10  total_streams                 200 non-null    int64
 11  streams_promedio_por_cancion  200 non-null    float64
 12  puntuacion_media              200 non-null    float64
 13  bailabilidad_media            200 non-null    float64
 14  energia_media                 200 non-null    float64
 15  mejor_posicion_chart          200 non-null    int64
 16  total_semanas_chart           200 non-null    int64
 17  num_playlists_total           200 non-null    int64
dtypes: float64(4), int64(10), object(4)
memory usage: 28.3+ KB

In [48]:
# Cambiamos el tipo de la columna anio_debut a DATE

artistas_rendimiento["anio_debut"] = pd.to_datetime(artistas_rendimiento["anio_debut"], format="%Y")

In [49]:
artistas_rendimiento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   artista_id                    200 non-null    int64
 1   nombre_artistico              200 non-null    object
 2   genero_principal              200 non-null    object
 3   pais_origen                   200 non-null    object
 4   anio_debut                    200 non-null    datetime64[ns]
 5   seguidores                    200 non-null    int64
 6   verificado                    200 non-null    int64
 7   sello_discografico            200 non-null    object
 8   num_canciones                 200 non-null    int64
 9   num_canciones_en_chart        200 non-null    int64
 10  total_streams                 200 non-null    int64
 11  streams_promedio_por_cancion  200 non-null    float64
 12  puntuacion_media              200 non-null    float64
 13  bailabilidad_media            200 non-null    float64
 14  energia_media                 200 non-null    float64
 15  mejor_posicion_chart          200 non-null    int64
 16  total_semanas_chart           200 non-null    int64
 17  num_playlists_total           200 non-null    int64
dtypes: datetime64[ns](1), float64(4), int64(9), object(4)
memory usage: 28.3+ KB

In [23]:
artistas_rendimiento.isnull().sum()

artista_id                      0
nombre_artistico                0
genero_principal                0
pais_origen                     0
anio_debut                      0
seguidores                      0
verificado                      0
sello_discografico              0
num_canciones                   0
num_canciones_en_chart          0
total_streams                   0
streams_promedio_por_cancion    0
puntuacion_media                0
bailabilidad_media              0
energia_media                   0
mejor_posicion_chart            0
total_semanas_chart             0
num_playlists_total             0
dtype: int64

####  Verificacion canciones_estadisticas

In [26]:
print(canciones_estadisticas.shape)

(2000, 27)

In [27]:
print(canciones_estadisticas.dtypes)

cancion_id                      int64
titulo                         object
artista_id                      int64
album                          object
anio_lanzamiento                int64
duracion_seg                    int64
genero                         object
subgenero                      object
energia                       float64
bailabilidad                  float64
valencia                      float64
acusticidad                   float64
instrumentalidad              float64
tempo                           int64
volumen_db                    float64
explicito                       int64
nombre_artistico               object
seguidores                      int64
total_reproducciones            int64
reproducciones_completadas    float64
ratio_completadas             float64
puntuacion_media              float64
num_valoraciones                int64
en_chart                        int64
mejor_posicion_chart            int64
semanas_en_chart                int64
num_playlists                   int64
dtype: object

In [29]:
canciones_estadisticas.head()

,cancion_id,titulo,artista_id,album,anio_lanzamiento,duracion_seg,genero,subgenero,energia,bailabilidad,...,seguidores,total_reproducciones,reproducciones_completadas,ratio_completadas,puntuacion_media,num_valoraciones,en_chart,mejor_posicion_chart,semanas_en_chart,num_playlists
0,1,Tema 1,72,Bob Marley - 25 Aniversario,2021,339,electronica,trance,0.86,0.63,...,2272315,35,29.0,0.8286,4.00,6,1,43,1,2
1,2,Tema 2,169,Francisco Stone - Evolución,2022,134,latin,salsa,0.64,0.87,...,134889,24,18.0,0.7500,3.17,6,1,13,4,8
2,3,Tema 3,80,Francisco Stone - Nuevo,2022,123,pop,pop-urbano,0.66,0.58,...,379450,26,19.0,0.7308,3.40,10,1,4,3,6
3,4,Tema 4,103,Francisco Stone - Segundo Album,2021,135,latin,cumbia,0.83,0.91,...,1142190,33,22.0,0.6667,4.08,12,1,26,3,7
4,5,Tema 5,108,Gabriel García - Vueltas,2022,200,pop,pop-latino,0.51,0.59,...,4236247,22,20.0,0.9091,2.71,7,1,12,1,4

In [28]:
print(canciones_estadisticas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cancion_id                  2000 non-null   int64
 1   titulo                      2000 non-null   object
 2   artista_id                  2000 non-null   int64
 3   album                       2000 non-null   object
 4   anio_lanzamiento            2000 non-null   int64
 5   duracion_seg                2000 non-null   int64
 6   genero                      2000 non-null   object
 7   subgenero                   2000 non-null   object
 8   energia                     2000 non-null   float64
 9   bailabilidad                2000 non-null   float64
 10  valencia                    2000 non-null   float64
 11  acusticidad                 2000 non-null   float64
 12  instrumentalidad            2000 non-null   float64
 13  tempo                       2000 non-null   int64
 14  volumen_db                  2000 non-null   float64
 15  explicito                   2000 non-null   int64
 16  nombre_artistico            2000 non-null   object
 17  seguidores                  2000 non-null   int64
 18  total_reproducciones        2000 non-null   int64
 19  reproducciones_completadas  2000 non-null   float64
 20  ratio_completadas           2000 non-null   float64
 21  puntuacion_media            2000 non-null   float64
 22  num_valoraciones            2000 non-null   int64
 23  en_chart                    2000 non-null   int64
 24  mejor_posicion_chart        2000 non-null   int64
 25  semanas_en_chart            2000 non-null   int64
 26  num_playlists               2000 non-null   int64
dtypes: float64(9), int64(13), object(5)
memory usage: 422.0+ KB
None

In [46]:
# Cambiamos el tipo de dato de 'anio_lanzamiento' a DATE
canciones_estadisticas["anio_lanzamiento"] = pd.to_datetime(canciones_estadisticas["anio_lanzamiento"], format="%Y")

In [47]:
print(canciones_estadisticas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cancion_id                  2000 non-null   int64
 1   titulo                      2000 non-null   object
 2   artista_id                  2000 non-null   int64
 3   album                       2000 non-null   object
 4   anio_lanzamiento            2000 non-null   datetime64[ns]
 5   duracion_seg                2000 non-null   int64
 6   genero                      2000 non-null   object
 7   subgenero                   2000 non-null   object
 8   energia                     2000 non-null   float64
 9   bailabilidad                2000 non-null   float64
 10  valencia                    2000 non-null   float64
 11  acusticidad                 2000 non-null   float64
 12  instrumentalidad            2000 non-null   float64
 13  tempo                       2000 non-null   int64
 14  volumen_db                  2000 non-null   float64
 15  explicito                   2000 non-null   int64
 16  nombre_artistico            2000 non-null   object
 17  seguidores                  2000 non-null   int64
 18  total_reproducciones        2000 non-null   int64
 19  reproducciones_completadas  2000 non-null   float64
 20  ratio_completadas           2000 non-null   float64
 21  puntuacion_media            2000 non-null   float64
 22  num_valoraciones            2000 non-null   int64
 23  en_chart                    2000 non-null   int64
 24  mejor_posicion_chart        2000 non-null   int64
 25  semanas_en_chart            2000 non-null   int64
 26  num_playlists               2000 non-null   int64
dtypes: datetime64[ns](1), float64(9), int64(12), object(5)
memory usage: 422.0+ KB
None

In [32]:
canciones_estadisticas.isnull().sum()

cancion_id                    0
titulo                        0
artista_id                    0
album                         0
anio_lanzamiento              0
duracion_seg                  0
genero                        0
subgenero                     0
energia                       0
bailabilidad                  0
valencia                      0
acusticidad                   0
instrumentalidad              0
tempo                         0
volumen_db                    0
explicito                     0
nombre_artistico              0
seguidores                    0
total_reproducciones          0
reproducciones_completadas    0
ratio_completadas             0
puntuacion_media              0
num_valoraciones              0
en_chart                      0
mejor_posicion_chart          0
semanas_en_chart              0
num_playlists                 0
dtype: int64

####  Verificacion generos_por_temporada

In [38]:
print(generos_por_temporada.shape)

(240, 9)

In [40]:
print(generos_por_temporada.dtypes)

anio                      int64
trimestre                 int64
temporada                object
genero                   object
total_streams             int64
usuarios_unicos           int64
ratio_completadas       float64
horas_escucha           float64
porcentaje_del_total    float64
dtype: object

In [41]:
generos_por_temporada.head()

,anio,trimestre,temporada,genero,total_streams,usuarios_unicos,ratio_completadas,horas_escucha,porcentaje_del_total
0,2024,4,Invierno,pop,138,134,65.22,8.54,3.33
1,2024,1,Invierno,rock,262,256,66.79,15.88,6.31
2,2024,1,Invierno,latin,245,240,71.84,15.39,5.90
3,2024,4,Invierno,indie,194,190,71.13,11.87,4.67
4,2024,4,Invierno,flamenco,126,124,76.98,7.76,3.04

In [42]:
print(generos_por_temporada.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   anio                  240 non-null    int64
 1   trimestre             240 non-null    int64
 2   temporada             240 non-null    object
 3   genero                240 non-null    object
 4   total_streams         240 non-null    int64
 5   usuarios_unicos       240 non-null    int64
 6   ratio_completadas     240 non-null    float64
 7   horas_escucha         240 non-null    float64
 8   porcentaje_del_total  240 non-null    float64
dtypes: float64(3), int64(4), object(2)
memory usage: 17.0+ KB
None

In [43]:
# Cambiamos la columna 'anio' a tipo DATE
generos_por_temporada["anio"] = pd.to_datetime(generos_por_temporada["anio"], format="%Y")

In [44]:
print(generos_por_temporada.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   anio                  240 non-null    datetime64[ns]
 1   trimestre             240 non-null    int64
 2   temporada             240 non-null    object
 3   genero                240 non-null    object
 4   total_streams         240 non-null    int64
 5   usuarios_unicos       240 non-null    int64
 6   ratio_completadas     240 non-null    float64
 7   horas_escucha         240 non-null    float64
 8   porcentaje_del_total  240 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(2)
memory usage: 17.0+ KB
None

In [50]:
generos_por_temporada.isnull().sum()

anio                    0
trimestre               0
temporada               0
genero                  0
total_streams           0
usuarios_unicos         0
ratio_completadas       0
horas_escucha           0
porcentaje_del_total    0
dtype: int64

####  Verificacion perfil_oyentes

In [51]:
print(perfil_oyentes.shape)

(5000, 17)

In [52]:
print(perfil_oyentes.dtypes)

usuario_id                      int64
edad                            int64
sexo                           object
ciudad                         object
tipo_suscripcion               object
fecha_registro                 object
dispositivo_principal          object
horas_escucha_mensual           int64
total_reproducciones            int64
canciones_distintas             int64
artistas_distintos              int64
ratio_completadas             float64
modo_reproduccion_favorito     object
reproducciones_fin_semana     float64
generos_distintos               int64
genero_favorito                object
puntuacion_media_dada         float64
dtype: object

In [53]:
perfil_oyentes.head()

,usuario_id,edad,sexo,ciudad,tipo_suscripcion,fecha_registro,dispositivo_principal,horas_escucha_mensual,total_reproducciones,canciones_distintas,artistas_distintos,ratio_completadas,modo_reproduccion_favorito,reproducciones_fin_semana,generos_distintos,genero_favorito,puntuacion_media_dada
0,1,40,M,Cádiz,premium,2021-06-22,movil,32,8,8,8,0.8750,recomendacion,25.00,6,rock,4.67
1,2,32,M,Girona,premium,2022-10-07,movil,34,7,7,7,0.7143,recomendacion,28.57,6,reggaeton,3.75
2,3,30,M,Cádiz,premium,2019-05-22,tablet,62,5,5,5,0.6000,album,40.00,4,clasica,3.50
3,4,13,No_especificado,Vigo,free,2019-11-03,pc,9,10,10,10,0.5000,playlist,30.00,5,pop,4.67
4,5,30,No_especificado,Granada,free,2022-07-22,tablet,56,10,10,10,0.8000,album,40.00,5,rap,4.67

In [54]:
print(perfil_oyentes.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   usuario_id                  5000 non-null   int64
 1   edad                        5000 non-null   int64
 2   sexo                        5000 non-null   object
 3   ciudad                      5000 non-null   object
 4   tipo_suscripcion            5000 non-null   object
 5   fecha_registro              5000 non-null   object
 6   dispositivo_principal       5000 non-null   object
 7   horas_escucha_mensual       5000 non-null   int64
 8   total_reproducciones        5000 non-null   int64
 9   canciones_distintas         5000 non-null   int64
 10  artistas_distintos          5000 non-null   int64
 11  ratio_completadas           5000 non-null   float64
 12  modo_reproduccion_favorito  5000 non-null   object
 13  reproducciones_fin_semana   5000 non-null   float64
 14  generos_distintos           5000 non-null   int64
 15  genero_favorito             5000 non-null   object
 16  puntuacion_media_dada       5000 non-null   float64
dtypes: float64(3), int64(7), object(7)
memory usage: 664.2+ KB
None

In [56]:
# Convertimos la columna 'fecha_registro' a tipo DATE
perfil_oyentes["fecha_registro"] = pd.to_datetime(perfil_oyentes["fecha_registro"], format="%Y-%m-%d")

In [57]:
print(perfil_oyentes.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   usuario_id                  5000 non-null   int64
 1   edad                        5000 non-null   int64
 2   sexo                        5000 non-null   object
 3   ciudad                      5000 non-null   object
 4   tipo_suscripcion            5000 non-null   object
 5   fecha_registro              5000 non-null   datetime64[ns]
 6   dispositivo_principal       5000 non-null   object
 7   horas_escucha_mensual       5000 non-null   int64
 8   total_reproducciones        5000 non-null   int64
 9   canciones_distintas         5000 non-null   int64
 10  artistas_distintos          5000 non-null   int64
 11  ratio_completadas           5000 non-null   float64
 12  modo_reproduccion_favorito  5000 non-null   object
 13  reproducciones_fin_semana   5000 non-null   float64
 14  generos_distintos           5000 non-null   int64
 15  genero_favorito             5000 non-null   object
 16  puntuacion_media_dada       5000 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(7), object(6)
memory usage: 664.2+ KB
None

In [55]:
perfil_oyentes.isnull().sum()

usuario_id                    0
edad                          0
sexo                          0
ciudad                        0
tipo_suscripcion              0
fecha_registro                0
dispositivo_principal         0
horas_escucha_mensual         0
total_reproducciones          0
canciones_distintas           0
artistas_distintos            0
ratio_completadas             0
modo_reproduccion_favorito    0
reproducciones_fin_semana     0
generos_distintos             0
genero_favorito               0
puntuacion_media_dada         0
dtype: int64

####  Verificacion streaming_mensual

In [58]:
print(streaming_mensual.shape)

(36, 11)

In [59]:
print(streaming_mensual.dtypes)

anio                      int64
mes                       int64
total_streams             int64
streams_completados     float64
usuarios_activos          int64
canciones_escuchadas      int64
horas_totales           float64
top_genero               object
streams_premium         float64
streams_free            float64
ratio_completadas       float64
dtype: object

In [60]:
streaming_mensual.head()

,anio,mes,total_streams,streams_completados,usuarios_activos,canciones_escuchadas,horas_totales,top_genero,streams_premium,streams_free,ratio_completadas
0,2022,1,1411,999.0,1231,995,84.71,indie,832.0,579.0,70.80
1,2022,2,1230,868.0,1090,913,75.00,r&b,736.0,494.0,70.57
2,2022,3,1450,1037.0,1258,1034,89.06,indie,852.0,598.0,71.52
3,2022,4,1350,956.0,1179,992,84.13,indie,799.0,551.0,70.81
4,2022,5,1458,1019.0,1266,1017,87.33,indie,859.0,599.0,69.89

In [ ]:
print(streaming_mensual.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   anio                  36 non-null     int64
 1   mes                   36 non-null     int64
 2   total_streams         36 non-null     int64
 3   streams_completados   36 non-null     float64
 4   usuarios_activos      36 non-null     int64
 5   canciones_escuchadas  36 non-null     int64
 6   horas_totales         36 non-null     float64
 7   top_genero            36 non-null     object
 8   streams_premium       36 non-null     float64
 9   streams_free          36 non-null     float64
 10  ratio_completadas     36 non-null     float64
dtypes: float64(5), int64(5), object(1)
memory usage: 3.2+ KB
None

In [62]:
# Cambiamos el tipo de dato de 'anio' y 'mes' a DATE
streaming_mensual["anio"] = pd.to_datetime(streaming_mensual["anio"], format="%Y")
streaming_mensual["mes"] = pd.to_datetime(streaming_mensual["mes"], format="%m")

In [63]:
print(streaming_mensual.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   anio                  36 non-null     datetime64[ns]
 1   mes                   36 non-null     datetime64[ns]
 2   total_streams         36 non-null     int64
 3   streams_completados   36 non-null     float64
 4   usuarios_activos      36 non-null     int64
 5   canciones_escuchadas  36 non-null     int64
 6   horas_totales         36 non-null     float64
 7   top_genero            36 non-null     object
 8   streams_premium       36 non-null     float64
 9   streams_free          36 non-null     float64
 10  ratio_completadas     36 non-null     float64
dtypes: datetime64[ns](2), float64(5), int64(3), object(1)
memory usage: 3.2+ KB
None

In [64]:
streaming_mensual.isnull().sum()

anio                    0
mes                     0
total_streams           0
streams_completados     0
usuarios_activos        0
canciones_escuchadas    0
horas_totales           0
top_genero              0
streams_premium         0
streams_free            0
ratio_completadas       0
dtype: int64

## 29. Limpieza de Datos